### ISSUE TITLE
Scripting coverage issue

### ISSUE THREAD

**Issue by peterdresslar** [Urigo/graphql-cli#547] opened 2019-10-28 09:25 UTC
**Describe the bug**
A path in the logic leaves `projectName` uncovered

**To Reproduce**
```
foo:dev peter$ graphql init
? Select the best option for you I have an existing project uses GraphQL.
? Do you want to generate the backend code using data model No
? Where is your schema? https://github.com/octokit/graphql-schema/blob/master/sc
hema.graphql
? projectType: Frontend only
? Where are your operation documents? ./
Error: You must provide a `name` parameter
    at ConfirmPrompt.throwParamError (/Users/peterdresslar/.config/yarn/global/node_modules/inquirer/lib/prompts/base.js:73:11)
    at new Prompt (/Users/peterdresslar/.config/yarn/global/node_modules/inquirer/lib/prompts/base.js:33:12)
    at new ConfirmPrompt 

...

ules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/peterdresslar/.config/yarn/global/node_modules/rxjs/internal/Subscriber.js:66:18)
```

**Comment by peterdresslar** [comment] 2019-10-28 09:28
It may be the case that this option is really an existing *GraphQL Config* project and is supposed to take a name from those documents. In that case, the script option should read:

`I have an existing GraphQL Config project using operation documents.`

**Comment by wtrocki** [comment] 2020-09-04 11:44
Duplicate of https://github.com/Urigo/graphql-cli/issues/1421

**Closed by wtrocki** 2020-09-04 11:44 UTC
