### ISSUE TITLE
Improve how `add-endpoint`/`add-project` deal with environment variables

### ISSUE THREAD

**Issue by kbrandwijk** [Urigo/graphql-cli#167] opened 2018-01-20 15:44 UTC
When you add an endpoint or a project using these commands, the values you enter will be hardcoded into the `.graphqlconfig` file. I think it would be an improvement if these commands would ask the user if the values should be stored directly, or through environment variables.

If so, the actual value should be stored in a .env file, and the references should be put in the `.graphqlconfig`.

This will reduce the manual steps needed to work with env vars.

**Comment by wtrocki** [comment] 2020-09-04 11:45
Duplicate of resolved issue: https://github.com/Urigo/graphql-cli/issues/331

**Closed by wtrocki** 2020-09-04 11:45 UTC
